// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ivrkXcB4gUnoy8HZBkIDu-hW1xf4pPQ',
    appId: '1:838350492511:web:1b20d83ba14047526a1cea',
    messagingSenderId: '838350492511',
    projectId: 'flutterfixitnow',
    authDomain: 'flutterfixitnow.firebaseapp.com',
    storageBucket: 'flutterfixitnow.firebasestorage.app',
    measurementId: 'G-QHYQBGRTGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc0UoJSTgOXxIXF6Be8hgQq7JiM3nwS34',
    appId: '1:838350492511:android:5fd347f9823fe8016a1cea',
    messagingSenderId: '838350492511',
    projectId: 'flutterfixitnow',
    storageBucket: 'flutterfixitnow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAftwf6Z7fHivnR7caQ9G1Cx-Bpc18tmH8',
    appId: '1:838350492511:ios:8ef95e804c1b1e516a1cea',
    messagingSenderId: '838350492511',
    projectId: 'flutterfixitnow',
    storageBucket: 'flutterfixitnow.firebasestorage.app',
    iosBundleId: 'com.example.flutterFixItNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAftwf6Z7fHivnR7caQ9G1Cx-Bpc18tmH8',
    appId: '1:838350492511:ios:8ef95e804c1b1e516a1cea',
    messagingSenderId: '838350492511',
    projectId: 'flutterfixitnow',
    storageBucket: 'flutterfixitnow.firebasestorage.app',
    iosBundleId: 'com.example.flutterFixItNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7ivrkXcB4gUnoy8HZBkIDu-hW1xf4pPQ',
    appId: '1:838350492511:web:0f6aae351f3fd59f6a1cea',
    messagingSenderId: '838350492511',
    projectId: 'flutterfixitnow',
    authDomain: 'flutterfixitnow.firebaseapp.com',
    storageBucket: 'flutterfixitnow.firebasestorage.app',
    measurementId: 'G-H1LMS2NMQ5',
  );
}
